site_name: Sam Allen - Technical Writer
theme:
    name: material
    palette:
      primary: green
    features:
      - navigation.tabs
      - toc.integrate
      - content.code.annotate
      - content.code.select
    favicon: favicon.png
    icon:
      logo: material/application-edit

extra:
  analytics:
    provider: google
    property: G-YVNHWV1LG8


plugins:
    - glightbox:
   #  slide_effect: none
   #    zoomable: false
   #    auto_caption: false
   #    caption_position: top
   #    width: 10%
   #    touchNavigation: false
   #    effect: fade
   #    draggable: false

#This hides the TOC, but it can be re-config'd to allow for header sizes in the TOC
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.details
  - admonition
  - toc:
      toc_depth: 4

extra_css:
  - stylesheets/extra.css


copyright: Copyright &copy; 2025 Sam Allen
