site_name: Sam Allen - Technical Writer
theme:
    name: material
    palette:
      primary: green
    features:
      - navigation.tabs
      - toc.integrate
    favicon: favicon.png

    #Testing my deploy setup

plugins:
   # - glightbox:
   #  slide_effect: none
   #    zoomable: false
   #    auto_caption: false
   #    caption_position: top
   #    width: 10%
   #    touchNavigation: false
   #    effect: fade
   #    draggable: false

#This hides the TOC, but it can be re-config'd to allow for header sizes in the TOC
markdown_extensions:
  - toc:
      toc_depth: 4

extra_css:
  - stylesheets/extra.css 

copyright: Copyright &copy; 2024 Sam Allen